import type { Metadata } from "next";
import "./globals.css";
import { inter } from "./fonts";
import NextAuthProvider from "./next-auth-provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <NextAuthProvider>
      <html lang="en">
        <body className={"border-2 border-blue-600 m-2 " + inter.className}>
          <div>LAYOUT ROOT</div>
          {children}
        </body>
      </html>
    </NextAuthProvider>
  );
}
